### ISSUE TITLE
reject(new Error('Something went wrong while loading ReCaptcha. (' + error.toString() + ')'));

### ISSUE THREAD

**Issue by Larsmyrup** [AurityLab/recaptcha-v3#109]
Hi

I'm using version 1.5 of this library (just upgraded to newest version, so that might fix it, but probably not as far as i can see from the logs).

A lot of my users are getting this mistake. All of them are on a Mobile Browser either Safari or Chrome. The problem occurs on both Android and iOS devices. I can't seem to reproduce the error myself, so it doesn't seem very consistent.

The error comes from ReCaptchaLoader.js line 72 looking like this:

reject(new Error('Something went wrong while loading ReCaptcha. (' + error.toString() + ')'));

So i might have done something wrong - but the console statement that is suppose to tell me the error doesn't seem to be working.

**Comment by WipeAir** [comment]
Hey,
thanks for reporting this bug!
I've just published v1.7.2 which should fix this issue. ReCaptchaLoader will now reject the actual error when the script fails to load, which should support your further debugging process.
