### ISSUE TITLE
Badge Position - Bottomleft

### ISSUE THREAD

**Issue by fcandiani** [AurityLab/recaptcha-v3#154]
I would like to know how to place the bagde on the bottom left of the screen. Using the data-badge="bottomleft"

Tried something like:

Vue.use(VueReCaptcha, { siteKey: '', loaderOptions: { renderParameters: { badge: 'bottomleft' } } })

https://developers.google.com/recaptcha/docs/invisible#render_param

https://github.com/AurityLab/vue-recaptcha-v3/issues/143

**Comment by WipeAir** [comment]
Hey, sorry for the delayed response.
I've addressed this issue in #172. The implemented functionallity in the PR will allow you pass the render parameters to the `load(...)` function.
The PR will be merged into the master within the next hours and a new version will also be released (I'll also update vue-recaptcha-v3).

**Comment by WipeAir** [comment]
Hey,
I've just published v1.8.0 which includes the the fix to set the `badge` property.
