### ISSUE TITLE
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by rezaffm** [AurityLab/recaptcha-v3#210]
Hi there. Just added your lib to my project and retrieved the token onload of a component. I get the following warning in Chrome Dev Console:

A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

Actually, I get this warning 5 times for several cookies that were set. The token itself is delivered tough. 

It's just a warning and the code works as expected - a fix would be to set the cookie with the "SameSite" attribute I pressume?

And thanks for the package btw.

**Comment by WipeAir** [comment]
Hey, sorry for the late reply. 
Sadly it's not as easy as just set the cookie with the attribute. The cookie which causes this message is set by Google.
Therefore we currently can't fix this problem on this library. But as this is just a warning, you can just ignore it until Google fixes the issue on their side.

(see https://stackoverflow.com/a/58375142)
