### ISSUE TITLE
reCaptcha invalid JSON response

### ISSUE THREAD

**Issue by RA9OAJ** [AurityLab/recaptcha-v3#240]
Faced an invalid JSON in the server response. Server response starts with ")]} '".
Found an old topic on [StackOverflow](https://stackoverflow.com/questions/36693906/recaptcha-invalid-json-response)
It seems that this is still relevant at the moment, maybe not always, but a similar server response comes as a check.
Maybe you should consider this when parsing the server response?

**Comment by WipeAir** [comment]
This library actually just depends on the official Google reCAPTCHA API. That basically means that this library does not send the actual request.
