### ISSUE TITLE
Make ReCaptchaInstance.execute action parameter optional

### ISSUE THREAD

**Issue by andyGallagher** [AurityLab/recaptcha-v3#268]
Hi,

Came across this during development and figured I'd raise a ticket.

Making the [`execute`](https://github.com/AurityLab/recaptcha-v3/blob/master/src/ReCaptchaInstance.ts#L26) function parameter action an optional parameter allows a user to not specify any particular action, which can be useful.

Please let me know what you think and if you would like for me to open up a PR.

Thanks!

**Comment by WipeAir** [comment]
Hey,
that's actually good idea! It seems that reCaptcha supports null for the action parameter without any problems.
I've just implemented it.

**Comment by tiavina-mika** [comment]
What's the different options for action?
