### ISSUE TITLE
Remove recaptcha floating icon

### ISSUE THREAD

**Issue by gladwinbobby** [AurityLab/recaptcha-v3#3]
Hi, I'm using the recaptcha in the login page. After logging in, I navigate to the dashboard page but still the recaptcha logo appears. Is there any way to remove it?

**Comment by WipeAir** [comment]
Hi,
sadly it was disallowed by Google for a long time, because it would break their TOS.
But as I can see [here](https://stackoverflow.com/a/44543771), they allow it now.
I'll implement this on the library later today, I'll keep you posted.

**Comment by WipeAir** [comment]
The implementation of the hiding functionallity should done.
To use it you can use the `autoHideBadge` loader option ([Documented here](https://github.com/AurityLab/recaptcha-v3/tree/v1.2.1#loader-options)) or the `hideBadge(...)`  method from the ReCaptchaInstance (Instance is returned by the `load(...)` method).
If you have any further questions don't hesitate to reach out.

**Comment by gladwinbobby** [comment]
Hi, Thanks for the quick fix but now I'm getting this error
`Uncaught (in promise) TypeError: _this.recaptcha.execute(...).then(...).catch is not a function
    at eval (ReCaptchaInstance.js?b3e0:9)
    at new Promise (<anonymous>)
    at ReCaptchaInstance.execute (ReCaptchaInstance.js?b3e0:8)`

**Comment by WipeAir** [comment]
Hi,
thanks for the report! It's fixed in **version 1.2.2**.

**Comment by WipeAir** [comment]
What do you mean by the term `API errors`? Errors from `grecaptcha.execute(...)` or during the loading process?

**Comment by gladwinbobby** [comment]
This is my login function,

```
login() {
      let payLoad = {
        email: this.email,
        password: this.password,
        recaptcha: this.recaptcha
      };
      this.$store
        .dispatch("login", payLoad)
        .then(response => {
          this.$router.push({ name: "dashboard" });
        })
        .catch(error => {
          this.isLoading = false;
          for (let key in error.response.data) {
            this.errorMessage = error.response.data[key][0];
          }
        });
    }
```

and this is the promise returned from vuex store,

```
login({
            commit
        }, payload) {
            return new Promise((resolve, reject) => {
                axios.post('login', payload)
                    .then(response => {
                        const authToken = response.data.auth_token
                        localStorage.setItem('auth_token', authToken)
                        commit('authSuccess', response.data)
                        resolve(response)
                    })
                    .catch(error => {
                        localStorage.removeItem('auth_token')
                        reject(error)
                    })
            })
        }
```
If the API call returns 400, It's not getting into the catch block.

**Comment by WipeAir** [comment]
Ok,
which catch block do you mean?
The one from the Axios Promise or from the vuex dispatch?

**Comment by gladwinbobby** [comment]
The one in vuex dispatch,
```
.catch(error => {
    localStorage.removeItem('auth_token')
    reject(error)
})
```

**Comment by WipeAir** [comment]
That's actually fully independent from this library.
Because you just call the login method and do not event return the promise there. Maybe something is wrong with Axios itself here.
