### ISSUE TITLE
autoHideBadge  is not working  

### ISSUE THREAD

**Issue by malahmad** [AurityLab/recaptcha-v3#5]
![image](https://user-images.githubusercontent.com/33462613/56862203-06757680-69b1-11e9-8729-064e56ecf878.png)

**Comment by malahmad** [comment]
I have enabled the autoHideBadge  option but is still shown on my website.

**Comment by WipeAir** [comment]
Thanks for reporting the issue!
It has been fixed in version `1.5.0`
