### ISSUE TITLE
RenderParameters not adding dark theme

### ISSUE THREAD

**Issue by CorneDeMeyer** [AurityLab/recaptcha-v3#56]
Hi There,

When attempting to add the dark theme as per 
[https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-v3-badge-what-is-allowed](url) the themes stays white

load(this.siteKey,
             {
               useRecaptchaNet: false,
               autoHideBadge: false,
               renderParameters:
                 {
                   'theme' : 'dark'
                 }
             }).then((recaptcha) => {
          recaptcha.execute('onSubmit').then((token) => { console.log(token); });

**Comment by WipeAir** [comment]
Hey,
I just looked into your issue.
It looks like reCAPTCHA **v3** simply does not support theming.
The documentation for available rendering parameters is kinda unclear at the moment.

(Sorry for the extremely delayed answer!)
