### ISSUE TITLE
Is there a way to reloading ReCapatcha? or setting custom URL for the js file?

### ISSUE THREAD

**Issue by Almo7aya** [AurityLab/recaptcha-v3#76]
Hello, Sometimes Recaptcha js file fails to load due to some network issues or government restrictions over google APIs anyway, Calling load again does not help the promise never call `then`, so we need to reset the package state on error so we can call load again and again to ensure that the Recaptcha js file has been loaded 

Edit: If we can also create a new option to pass the URL of the Recaptcha js file in case we want to change to a new one

**Comment by WipeAir** [comment]
Hey,
thanks for your contribution!  I've published `v1.7.0` which contains your commits.
